export default function getPersonals() {
  return {
    page0: [
      {
        name: 'Maribel Rutherford',
        position: 'Junior Java Script Developer',
        office: 'Delaware',
        age: 34,
        startDate: '1997/05/05',
        salary: '359',
      },
      {
        name: 'Jeanne Thiel',
        position: 'Senior Marketing Designer',
        office: 'New Mexico',
        age: 39,
        startDate: '1972/07/19',
        salary: '1286',
      },
      {
        name: 'Shaina Rutherford',
        position: 'Marketing Designer',
        office: 'Georgia',
        age: 41,
        startDate: '2014/12/10',
        salary: '1247',
      },
      {
        name: 'Jorge Brakus',
        position: 'Personnel Lead',
        office: 'Florida',
        age: 34,
        startDate: '1989/01/22',
        salary: '1205',
      },
      {
        name: 'Daron Walker',
        position: 'Junior Java Script Developer',
        office: 'West Virginia',
        age: 47,
        startDate: '2005/07/25',
        salary: '536',
      },
      {
        name: 'Casey Crist',
        position: 'Support Lead',
        office: 'Mississippi',
        age: 46,
        startDate: '1979/04/28',
        salary: '737',
      },
      {
        name: 'Jalyn McDermott',
        position: 'Sales Assistant',
        office: 'Washington',
        age: 36,
        startDate: '2005/10/23',
        salary: '1438',
      },
      {
        name: 'Alysson Hayes',
        position: 'Sales Assistant',
        office: 'West Virginia',
        age: 48,
        startDate: '1975/03/02',
        salary: '792',
      },
      {
        name: 'Felipa Jacobs',
        position: 'Support Lead',
        office: 'Minnesota',
        age: 39,
        startDate: '1970/03/24',
        salary: '1214',
      },
      {
        name: 'Kailee Olson',
        position: 'Personnel Lead',
        office: 'Utah',
        age: 33,
        startDate: '2001/02/08',
        salary: '1460',
      },
    ],
    page1: [
      {
        name: 'Mac Anderson',
        position: 'Marketing Designer',
        office: 'South Carolina',
        age: 35,
        startDate: '1994/10/26',
        salary: '542',
      },
      {
        name: 'Lon Fay',
        position: 'Sales Assistant',
        office: 'Vermont',
        age: 32,
        startDate: '2015/11/29',
        salary: '1467',
      },
      {
        name: 'Daryl Kulas',
        position: 'Senior Marketing Designer',
        office: 'Alabama',
        age: 42,
        startDate: '2001/02/28',
        salary: '1277',
      },
      {
        name: 'Donald Schultz',
        position: 'Marketing Designer',
        office: 'Arizona',
        age: 35,
        startDate: '1971/11/16',
        salary: '209',
      },
      {
        name: 'Furman Mraz',
        position: 'Software Engineer',
        office: 'Kansas',
        age: 42,
        startDate: '1986/02/09',
        salary: '203',
      },
      {
        name: 'Harmon Hodkiewicz',
        position: 'Designer',
        office: 'Missouri',
        age: 39,
        startDate: '1984/03/25',
        salary: '1105',
      },
      {
        name: 'Kyle Cronin',
        position: 'Designer',
        office: 'Mississippi',
        age: 42,
        startDate: '1984/09/01',
        salary: '177',
      },
      {
        name: 'Stephany Conn',
        position: 'Designer',
        office: 'New Hampshire',
        age: 30,
        startDate: '1991/06/21',
        salary: '340',
      },
      {
        name: 'Lazaro Nikolaus',
        position: 'Junior Java Script Developer',
        office: 'Montana',
        age: 45,
        startDate: '1999/09/28',
        salary: '1085',
      },
      {
        name: 'Clay Sanford',
        position: 'Sales Assistant',
        office: 'Pennsylvania',
        age: 37,
        startDate: '1994/06/05',
        salary: '167',
      },
    ],
    page2: [
      {
        name: 'Amira Herman',
        position: 'Personnel Lead',
        office: 'New York',
        age: 46,
        startDate: '1998/03/19',
        salary: '814',
      },
      {
        name: 'Helene Kertzmann',
        position: 'Junior Java Script Developer',
        office: 'Virginia',
        age: 46,
        startDate: '1973/01/04',
        salary: '849',
      },
      {
        name: 'Yoshiko Stehr',
        position: 'Junior Java Script Developer',
        office: 'Georgia',
        age: 38,
        startDate: '2001/06/07',
        salary: '1128',
      },
      {
        name: 'Myah Nitzsche',
        position: 'Software Engineer',
        office: 'Alaska',
        age: 37,
        startDate: '1977/12/29',
        salary: '1301',
      },
      {
        name: 'Dylan Aufderhar',
        position: 'Designer',
        office: 'Illinois',
        age: 37,
        startDate: '1986/03/19',
        salary: '552',
      },
      {
        name: 'Cletus Kessler',
        position: 'Junior Java Script Developer',
        office: 'Nebraska',
        age: 40,
        startDate: '1990/05/09',
        salary: '579',
      },
      {
        name: 'Norene Ernser',
        position: 'Designer',
        office: 'Mississippi',
        age: 46,
        startDate: '2011/03/11',
        salary: '1299',
      },
      {
        name: 'Miles Vandervort',
        position: 'Junior Java Script Developer',
        office: 'Minnesota',
        age: 32,
        startDate: '1988/05/19',
        salary: '682',
      },
      {
        name: 'Jessy Williamson',
        position: 'Marketing Designer',
        office: 'Utah',
        age: 34,
        startDate: '1993/03/27',
        salary: '1287',
      },
      {
        name: 'Demetrius Crooks',
        position: 'Junior Java Script Developer',
        office: 'New Hampshire',
        age: 33,
        startDate: '2008/09/19',
        salary: '1334',
      },
    ],
    page3: [
      {
        name: 'Watson Fahey',
        position: 'Support Lead',
        office: 'Kentucky',
        age: 41,
        startDate: '2005/03/28',
        salary: '273',
      },
      {
        name: 'Niko Sauer',
        position: 'Marketing Designer',
        office: 'Delaware',
        age: 32,
        startDate: '2006/06/10',
        salary: '283',
      },
      {
        name: 'Merlin Bosco',
        position: 'Junior Java Script Developer',
        office: 'Illinois',
        age: 49,
        startDate: '2001/02/27',
        salary: '273',
      },
      {
        name: 'Gavin Tillman',
        position: 'Marketing Designer',
        office: 'Ohio',
        age: 33,
        startDate: '1988/06/19',
        salary: '940',
      },
      {
        name: 'Ian Eichmann',
        position: 'Personnel Lead',
        office: 'New Mexico',
        age: 41,
        startDate: '1983/12/23',
        salary: '397',
      },
      {
        name: 'Dayna Block',
        position: 'Designer',
        office: 'Utah',
        age: 36,
        startDate: '1975/10/25',
        salary: '1203',
      },
      {
        name: 'Sylvia Ebert',
        position: 'Designer',
        office: 'Louisiana',
        age: 30,
        startDate: '2008/07/05',
        salary: '1042',
      },
      {
        name: 'Margarita Altenwerth',
        position: 'Support Lead',
        office: 'Rhode Island',
        age: 49,
        startDate: '1993/08/14',
        salary: '145',
      },
      {
        name: 'Elvis Bradtke',
        position: 'Sales Assistant',
        office: 'Arizona',
        age: 45,
        startDate: '2004/08/08',
        salary: '690',
      },
      {
        name: 'Celia Leuschke',
        position: 'Marketing Designer',
        office: 'Missouri',
        age: 34,
        startDate: '1985/08/05',
        salary: '678',
      },
    ],
    page4: [
      {
        name: 'Jerald Skiles',
        position: 'Senior Marketing Designer',
        office: 'Louisiana',
        age: 49,
        startDate: '2004/06/18',
        salary: '1351',
      },
      {
        name: 'Francisco Stoltenberg',
        position: 'Marketing Designer',
        office: 'Idaho',
        age: 30,
        startDate: '2005/02/05',
        salary: '537',
      },
      {
        name: 'Destin Cruickshank',
        position: 'Developer',
        office: 'Connecticut',
        age: 41,
        startDate: '2001/06/05',
        salary: '1339',
      },
      {
        name: 'Claire Koch',
        position: 'Personnel Lead',
        office: 'Texas',
        age: 35,
        startDate: '1977/03/09',
        salary: '1104',
      },
      {
        name: 'Abbie Hermann',
        position: 'Software Engineer',
        office: 'Wisconsin',
        age: 35,
        startDate: '1982/02/28',
        salary: '647',
      },
      {
        name: 'Clovis Gutkowski',
        position: 'Software Engineer',
        office: 'New Mexico',
        age: 39,
        startDate: '2009/09/01',
        salary: '1374',
      },
      {
        name: 'Novella Larkin',
        position: 'Designer',
        office: 'Oklahoma',
        age: 35,
        startDate: '2000/02/16',
        salary: '1298',
      },
      {
        name: 'Hailie Upton',
        position: 'Marketing Designer',
        office: 'New York',
        age: 45,
        startDate: '1976/12/03',
        salary: '884',
      },
      {
        name: 'Jaydon Rau',
        position: 'Software Engineer',
        office: 'Tennessee',
        age: 34,
        startDate: '1979/09/17',
        salary: '303',
      },
      {
        name: 'Verla Skiles',
        position: 'Software Engineer',
        office: 'New Mexico',
        age: 37,
        startDate: '1984/01/05',
        salary: '873',
      },
    ],
    page5: [
      {
        name: 'Rebecca Hegmann',
        position: 'Software Engineer',
        office: 'Alaska',
        age: 42,
        startDate: '1983/06/19',
        salary: '200',
      },
      {
        name: 'Bradly Fay',
        position: 'Marketing Designer',
        office: 'Nevada',
        age: 33,
        startDate: '2006/05/10',
        salary: '1029',
      },
      {
        name: 'Hazel Hyatt',
        position: 'Designer',
        office: 'Minnesota',
        age: 46,
        startDate: '1986/03/26',
        salary: '799',
      },
      {
        name: 'Fidel Stroman',
        position: 'Designer',
        office: 'Georgia',
        age: 46,
        startDate: '2002/11/01',
        salary: '1411',
      },
      {
        name: 'Zelda Roberts',
        position: 'Software Engineer',
        office: 'Michigan',
        age: 43,
        startDate: '2006/08/27',
        salary: '697',
      },
      {
        name: 'Federico Rohan',
        position: 'Senior Marketing Designer',
        office: 'Wisconsin',
        age: 29,
        startDate: '1982/03/10',
        salary: '1450',
      },
      {
        name: 'Bennie Schaden',
        position: 'Junior Java Script Developer',
        office: 'Pennsylvania',
        age: 47,
        startDate: '2014/04/19',
        salary: '405',
      },
      {
        name: 'Samir Conroy',
        position: 'Marketing Designer',
        office: 'Georgia',
        age: 41,
        startDate: '1981/09/10',
        salary: '918',
      },
      {
        name: 'Nolan Sporer',
        position: 'Software Engineer',
        office: 'North Carolina',
        age: 41,
        startDate: '1982/05/23',
        salary: '1185',
      },
      {
        name: 'Mollie Gorczany',
        position: 'Software Engineer',
        office: 'Georgia',
        age: 30,
        startDate: '2015/11/15',
        salary: '530',
      },
    ],
    page6: [
      {
        name: 'Jules Larkin',
        position: 'Support Lead',
        office: 'New York',
        age: 34,
        startDate: '2009/04/30',
        salary: '899',
      },
      {
        name: 'Joan Toy',
        position: 'Personnel Lead',
        office: 'Louisiana',
        age: 49,
        startDate: '1995/08/19',
        salary: '1415',
      },
      {
        name: 'Crystal Dooley',
        position: 'Senior Marketing Designer',
        office: 'Idaho',
        age: 39,
        startDate: '1983/05/24',
        salary: '232',
      },
      {
        name: 'Santino Larson',
        position: 'Designer',
        office: 'West Virginia',
        age: 31,
        startDate: '1997/07/10',
        salary: '721',
      },
      {
        name: 'Erich Rogahn',
        position: 'Senior Marketing Designer',
        office: 'Maine',
        age: 35,
        startDate: '1980/08/09',
        salary: '143',
      },
      {
        name: 'Catharine Nader',
        position: 'Support Lead',
        office: 'North Carolina',
        age: 39,
        startDate: '1995/06/27',
        salary: '356',
      },
      {
        name: 'Dante Moore',
        position: 'Senior Marketing Designer',
        office: 'Louisiana',
        age: 43,
        startDate: '2009/03/06',
        salary: '1343',
      },
      {
        name: 'Destinee Brown',
        position: 'Software Engineer',
        office: 'Montana',
        age: 46,
        startDate: '2012/03/19',
        salary: '1237',
      },
      {
        name: 'Kamryn Wintheiser',
        position: 'Designer',
        office: 'Wisconsin',
        age: 36,
        startDate: '1979/06/26',
        salary: '218',
      },
      {
        name: 'Diamond Metz',
        position: 'Marketing Designer',
        office: 'Texas',
        age: 40,
        startDate: '1973/08/24',
        salary: '865',
      },
    ],
    page7: [
      {
        name: 'Bret McDermott',
        position: 'Designer',
        office: 'Wyoming',
        age: 42,
        startDate: '1982/06/16',
        salary: '1364',
      },
      {
        name: 'Solon Leuschke',
        position: 'Software Engineer',
        office: 'Colorado',
        age: 47,
        startDate: '1986/04/27',
        salary: '282',
      },
      {
        name: 'Malcolm Kuhic',
        position: 'Developer',
        office: 'Oregon',
        age: 41,
        startDate: '1972/02/23',
        salary: '338',
      },
      {
        name: 'Abelardo Schowalter',
        position: 'Software Engineer',
        office: 'Iowa',
        age: 46,
        startDate: '2010/02/02',
        salary: '893',
      },
      {
        name: 'Weston Lang',
        position: 'Developer',
        office: 'Idaho',
        age: 31,
        startDate: '1986/10/08',
        salary: '1274',
      },
      {
        name: 'Jayme Kunze',
        position: 'Personnel Lead',
        office: 'Rhode Island',
        age: 30,
        startDate: '1993/08/01',
        salary: '660',
      },
      {
        name: 'Judah Blick',
        position: 'Personnel Lead',
        office: 'Vermont',
        age: 47,
        startDate: '1992/10/22',
        salary: '1317',
      },
      {
        name: 'Guy Kuvalis',
        position: 'Developer',
        office: 'Massachusetts',
        age: 34,
        startDate: '2013/10/16',
        salary: '799',
      },
      {
        name: 'Aliyah Yost',
        position: 'Support Lead',
        office: 'Alabama',
        age: 29,
        startDate: '2015/06/18',
        salary: '1191',
      },
      {
        name: 'Rafaela Dibbert',
        position: 'Senior Marketing Designer',
        office: 'Nevada',
        age: 45,
        startDate: '1987/02/23',
        salary: '831',
      },
    ],
    page8: [
      {
        name: 'Julien Swaniawski',
        position: 'Support Lead',
        office: 'Colorado',
        age: 34,
        startDate: '1991/02/12',
        salary: '696',
      },
      {
        name: 'Jacey Bayer',
        position: 'Software Engineer',
        office: 'Missouri',
        age: 42,
        startDate: '1990/05/18',
        salary: '416',
      },
      {
        name: 'Elroy Conroy',
        position: 'Personnel Lead',
        office: 'Mississippi',
        age: 32,
        startDate: '2007/04/22',
        salary: '460',
      },
      {
        name: 'Rasheed McLaughlin',
        position: 'Sales Assistant',
        office: 'New York',
        age: 39,
        startDate: '1998/03/28',
        salary: '660',
      },
      {
        name: 'Trevion Haag',
        position: 'Support Lead',
        office: 'Arkansas',
        age: 45,
        startDate: '1992/07/10',
        salary: '320',
      },
      {
        name: 'Elian Casper',
        position: 'Software Engineer',
        office: 'Hawaii',
        age: 36,
        startDate: '2016/01/03',
        salary: '980',
      },
      {
        name: 'Irwin Leffler',
        position: 'Support Lead',
        office: 'Wisconsin',
        age: 45,
        startDate: '1971/05/26',
        salary: '708',
      },
      {
        name: 'Emilie Osinski',
        position: 'Developer',
        office: 'New York',
        age: 36,
        startDate: '1997/08/13',
        salary: '375',
      },
      {
        name: 'Arlene Sanford',
        position: 'Sales Assistant',
        office: 'Connecticut',
        age: 40,
        startDate: '2015/12/05',
        salary: '913',
      },
      {
        name: 'Linnea Parker',
        position: 'Software Engineer',
        office: 'North Dakota',
        age: 47,
        startDate: '1996/01/06',
        salary: '921',
      },
    ],
    page9: [
      {
        name: 'Tracy Johnson',
        position: 'Support Lead',
        office: 'North Dakota',
        age: 49,
        startDate: '1975/04/27',
        salary: '1261',
      },
      {
        name: 'Enola Bogisich',
        position: 'Developer',
        office: 'Hawaii',
        age: 35,
        startDate: '1986/02/10',
        salary: '686',
      },
      {
        name: 'Jaren Monahan',
        position: 'Developer',
        office: 'Pennsylvania',
        age: 32,
        startDate: '2002/08/19',
        salary: '310',
      },
      {
        name: 'Johathan Yundt',
        position: 'Designer',
        office: 'Nebraska',
        age: 35,
        startDate: '1991/11/21',
        salary: '972',
      },
      {
        name: 'Minnie Lang',
        position: 'Junior Java Script Developer',
        office: 'Vermont',
        age: 44,
        startDate: '1974/02/03',
        salary: '714',
      },
      {
        name: 'Kathleen Stroman',
        position: 'Designer',
        office: 'Nevada',
        age: 36,
        startDate: '1975/04/27',
        salary: '96',
      },
      {
        name: 'Laurianne Swaniawski',
        position: 'Designer',
        office: 'Michigan',
        age: 48,
        startDate: '1997/06/28',
        salary: '573',
      },
      {
        name: 'Lia Dickens',
        position: 'Personnel Lead',
        office: 'New Hampshire',
        age: 36,
        startDate: '2013/06/14',
        salary: '799',
      },
      {
        name: 'Aiyana Mueller',
        position: 'Marketing Designer',
        office: 'Maryland',
        age: 49,
        startDate: '2003/11/18',
        salary: '440',
      },
      {
        name: 'Kobe Lesch',
        position: 'Software Engineer',
        office: 'Mississippi',
        age: 30,
        startDate: '2001/05/31',
        salary: '1082',
      },
    ],
  };
}
